const std = @import("std");
const Memory = @import("../memory.zig").Memory;
const ops = @import("ops.zig");

pub const Flags = packed struct(u8) {
    zerobits: u4 = 0x00,
    c: u1,
    h: u1,
    n: u1,
    z: u1,

    pub fn format(self: Flags, writer: anytype) !void {
        try writer.print("Flags:\n", .{});
        try writer.print("Z: 0x{X}", .{self.z});
        try writer.print(" N: 0x{X}", .{self.n});
        try writer.print(" H: 0x{X}", .{self.h});
        try writer.print(" C: 0x{X}\n", .{self.c});
        try writer.print("Bits 3-0: 0x{X:0<4}", .{self.zerobits});
    }
};

const AF = packed union { pair: u16, bytes: packed struct(u16) {
    f: Flags,
    a: u8,
} };

const BC = packed union { pair: u16, bytes: packed struct(u16) { c: u8, b: u8 } };

const DE = packed union { pair: u16, bytes: packed struct(u16) { e: u8, d: u8 } };

const HL = packed union { pair: u16, bytes: packed struct(u16) { l: u8, h: u8 } };

pub const Registers = packed struct(u96) {
    af: AF = .{ .pair = 0x01B0 },
    bc: BC = .{ .pair = 0x0013 },
    de: DE = .{ .pair = 0x00D8 },
    hl: HL = .{ .pair = 0x014D },
    pc: u16 = 0x0100,
    sp: u16 = 0xFFFE,

    pub fn format(
        self: Registers,
        writer: anytype,
    ) !void {
        try writer.print("Registers\n", .{});
        try writer.print("AF pair:  0x{X:0>4}\n", .{self.af.pair});
        try writer.print("BC pair:  0x{X:0>4}\n", .{self.bc.pair});
        try writer.print("DE pair:  0x{X:0>4}\n", .{self.de.pair});
        try writer.print("HL pair:  0x{X:0>4}\n", .{self.hl.pair});
        try writer.print("PC:       0x{X:0>4}\n", .{self.pc});
        try writer.print("SP:       0x{X:0>4}\n", .{self.sp});
        try writer.print("{f}\n", .{self.af.bytes.f});
    }
};

pub const Cpu = struct {
    registers: Registers = .{},
    ime: bool = false,

    pub fn step(self: *Cpu, memory: *Memory) void {
        // std.debug.print("PC=0x{X:0>4}: ", .{self.registers.pc});
        const opcode = memory.read(self.registers.pc);
        self.increment_pc();
        self.execute(opcode, memory);
        // std.debug.print("{f}\n", .{self.registers});
    }

    pub fn increment_pc(self: *Cpu) void {
        self.registers.pc +%= 0x0001;
    }

    pub fn execute(self: *Cpu, opcode: u8, memory: *Memory) void {
        switch (opcode) {
            0x00 => ops.nop(self, memory),
            0x01 => ops.ld_bc_nn(self, memory),
            0x02 => ops.ld_bc_a(self, memory),
            0x03 => ops.inc_bc(self, memory),
            0x04 => ops.inc_b(self, memory),
            0x05 => ops.dec_b(self, memory),
            0x06 => ops.ld_b_n(self, memory),
            0x07 => ops.rlca(self, memory),
            0x08 => ops.ld_nn_sp(self, memory),
            0x09 => ops.add_hl_bc(self, memory),
            0x0A => ops.ld_a_bc(self, memory),
            0x0B => ops.dec_bc(self, memory),
            0x0C => ops.inc_c(self, memory),
            0x0D => ops.dec_c(self, memory),
            0x0E => ops.ld_c_n(self, memory),
            0x0F => ops.rrca(self, memory),
            0x10 => ops.stop(self, memory),
            0x11 => ops.ld_de_nn(self, memory),
            0x12 => ops.ld_de_a(self, memory),
            0x13 => ops.inc_de(self, memory),
            0x14 => ops.inc_d(self, memory),
            0x15 => ops.dec_d(self, memory),
            0x16 => ops.ld_d_n(self, memory),
            0x17 => ops.rla(self, memory),
            0x18 => ops.jr_n(self, memory),
            0x19 => ops.add_hl_de(self, memory),
            0x1A => ops.ld_a_de(self, memory),
            0x1B => ops.dec_de(self, memory),
            0x1C => ops.inc_e(self, memory),
            0x1D => ops.dec_e(self, memory),
            0x1E => ops.ld_e_n(self, memory),
            0x1F => ops.rra(self, memory),
            0x20 => ops.jr_nz_n(self, memory),
            0x21 => ops.ld_hl_nn(self, memory),
            0x22 => ops.ldi_hl_a(self, memory),
            0x23 => ops.inc_hl(self, memory),
            0x24 => ops.inc_h(self, memory),
            0x25 => ops.dec_h(self, memory),
            0x26 => ops.ld_h_n(self, memory),
            0x27 => ops.daa(self, memory),
            0x28 => ops.jr_z_n(self, memory),
            0x29 => ops.add_hl_hl(self, memory),
            0x2A => ops.ldi_a_hl(self, memory),
            0x2B => ops.dec_hl(self, memory),
            0x2C => ops.inc_l(self, memory),
            0x2D => ops.dec_l(self, memory),
            0x2E => ops.ld_l_n(self, memory),
            0x2F => ops.cpl(self, memory),
            0x30 => ops.jr_nc_n(self, memory),
            0x31 => ops.ld_sp_nn(self, memory),
            0x32 => ops.ldd_hl_a(self, memory),
            0x33 => ops.inc_sp(self, memory),
            0x34 => ops.inc_hli(self, memory),
            0x35 => ops.dec_hli(self, memory),
            0x36 => ops.ld_hli_n(self, memory),
            0x37 => ops.scf(self, memory),
            0x38 => ops.jr_c_n(self, memory),
            0x39 => ops.add_hl_sp(self, memory),
            0x3A => ops.ldd_a_hl(self, memory),
            0x3B => ops.dec_sp(self, memory),
            0x3C => ops.inc_a(self, memory),
            0x3D => ops.dec_a(self, memory),
            0x3E => ops.ld_a_n(self, memory),
            0x3F => ops.ccf(self, memory),
            0x40 => ops.ld_b_b(self),
            0x41 => ops.ld_b_c(self),
            0x42 => ops.ld_b_d(self),
            0x43 => ops.ld_b_e(self),
            0x44 => ops.ld_b_h(self),
            0x45 => ops.ld_b_l(self),
            0x46 => ops.ld_b_hli(self, memory),
            0x47 => ops.ld_b_a(self),
            0x48 => ops.ld_c_b(self),
            0x49 => ops.ld_c_c(self),
            0x4A => ops.ld_c_d(self),
            0x4B => ops.ld_c_e(self),
            0x4C => ops.ld_c_h(self),
            0x4D => ops.ld_c_l(self),
            0x4E => ops.ld_c_hli(self, memory),
            0x4F => ops.ld_c_a(self),
            0x50 => ops.ld_d_b(self),
            0x51 => ops.ld_d_c(self),
            0x52 => ops.ld_d_d(self),
            0x53 => ops.ld_d_e(self),
            0x54 => ops.ld_d_h(self),
            0x55 => ops.ld_d_l(self),
            0x56 => ops.ld_d_hli(self, memory),
            0x57 => ops.ld_d_a(self),
            0x58 => ops.ld_e_b(self),
            0x59 => ops.ld_e_c(self),
            0x5A => ops.ld_e_d(self),
            0x5B => ops.ld_e_e(self),
            0x5C => ops.ld_e_h(self),
            0x5D => ops.ld_e_l(self),
            0x5E => ops.ld_e_hli(self, memory),
            0x5F => ops.ld_e_a(self),
            0x60 => ops.ld_h_b(self),
            0x61 => ops.ld_h_c(self),
            0x62 => ops.ld_h_d(self),
            0x63 => ops.ld_h_e(self),
            0x64 => ops.ld_h_h(self),
            0x65 => ops.ld_h_l(self),
            0x66 => ops.ld_h_hli(self, memory),
            0x67 => ops.ld_h_a(self),
            0x68 => ops.ld_l_b(self),
            0x69 => ops.ld_l_c(self),
            0x6A => ops.ld_l_d(self),
            0x6B => ops.ld_l_e(self),
            0x6C => ops.ld_l_h(self),
            0x6D => ops.ld_l_l(self),
            0x6E => ops.ld_l_hli(self, memory),
            0x6F => ops.ld_l_a(self),
            0x70 => ops.ld_hli_b(self, memory),
            0x71 => ops.ld_hli_c(self, memory),
            0x72 => ops.ld_hli_d(self, memory),
            0x73 => ops.ld_hli_e(self, memory),
            0x74 => ops.ld_hli_h(self, memory),
            0x75 => ops.ld_hli_l(self, memory),
            0x76 => ops.halt(self, memory),
            0x77 => ops.ld_hli_a(self, memory),
            0x78 => ops.ld_a_b(self),
            0x79 => ops.ld_a_c(self),
            0x7A => ops.ld_a_d(self),
            0x7B => ops.ld_a_e(self),
            0x7C => ops.ld_a_h(self),
            0x7D => ops.ld_a_l(self),
            0x7E => ops.ld_a_hli(self, memory),
            0x7F => ops.ld_a_a(self),
            0x80 => ops.add_a_b(self, memory),
            0x81 => ops.add_a_c(self, memory),
            0x82 => ops.add_a_d(self, memory),
            0x83 => ops.add_a_e(self, memory),
            0x84 => ops.add_a_h(self, memory),
            0x85 => ops.add_a_l(self, memory),
            0x86 => ops.add_a_hli(self, memory),
            0x87 => ops.add_a_a(self, memory),
            0x88 => ops.adc_a_b(self, memory),
            0x89 => ops.adc_a_c(self, memory),
            0x8A => ops.adc_a_d(self, memory),
            0x8B => ops.adc_a_e(self, memory),
            0x8C => ops.adc_a_h(self, memory),
            0x8D => ops.adc_a_l(self, memory),
            0x8E => ops.adc_a_hli(self, memory),
            0x8F => ops.adc_a_a(self, memory),
            0x90 => ops.sub_a_b(self, memory),
            0x91 => ops.sub_a_c(self, memory),
            0x92 => ops.sub_a_d(self, memory),
            0x93 => ops.sub_a_e(self, memory),
            0x94 => ops.sub_a_h(self, memory),
            0x95 => ops.sub_a_l(self, memory),
            0x96 => ops.sub_a_hli(self, memory),
            0x97 => ops.sub_a_a(self, memory),
            0x98 => ops.sbc_a_b(self, memory),
            0x99 => ops.sbc_a_c(self, memory),
            0x9A => ops.sbc_a_d(self, memory),
            0x9B => ops.sbc_a_e(self, memory),
            0x9C => ops.sbc_a_h(self, memory),
            0x9D => ops.sbc_a_l(self, memory),
            0x9E => ops.sbc_a_hli(self, memory),
            0x9F => ops.sbc_a_a(self, memory),
            0xA0 => ops.and_b(self, memory),
            0xA1 => ops.and_c(self, memory),
            0xA2 => ops.and_d(self, memory),
            0xA3 => ops.and_e(self, memory),
            0xA4 => ops.and_h(self, memory),
            0xA5 => ops.and_l(self, memory),
            0xA6 => ops.and_hli(self, memory),
            0xA7 => ops.and_a(self, memory),
            0xA8 => ops.xor_b(self, memory),
            0xA9 => ops.xor_c(self, memory),
            0xAA => ops.xor_d(self, memory),
            0xAB => ops.xor_e(self, memory),
            0xAC => ops.xor_h(self, memory),
            0xAD => ops.xor_l(self, memory),
            0xAE => ops.xor_hli(self, memory),
            0xAF => ops.xor_a(self, memory),
            0xB0 => ops.or_b(self, memory),
            0xB1 => ops.or_c(self, memory),
            0xB2 => ops.or_d(self, memory),
            0xB3 => ops.or_e(self, memory),
            0xB4 => ops.or_h(self, memory),
            0xB5 => ops.or_l(self, memory),
            0xB6 => ops.or_hli(self, memory),
            0xB7 => ops.or_a(self, memory),
            0xB8 => ops.cp_b(self, memory),
            0xB9 => ops.cp_c(self, memory),
            0xBA => ops.cp_d(self, memory),
            0xBB => ops.cp_e(self, memory),
            0xBC => ops.cp_h(self, memory),
            0xBD => ops.cp_l(self, memory),
            0xBE => ops.cp_hli(self, memory),
            0xBF => ops.cp_a(self, memory),
            0xC0 => ops.ret_nz(self, memory),
            0xC1 => ops.pop_bc(self, memory),
            0xC2 => ops.jp_nz_nn(self, memory),
            0xC3 => ops.jp_nn(self, memory),
            0xC4 => ops.call_nz_nn(self, memory),
            0xC5 => ops.push_bc(self, memory),
            0xC6 => ops.add_a_n(self, memory),
            0xC7 => ops.rst_00(self, memory),
            0xC8 => ops.ret_z(self, memory),
            0xC9 => ops.ret(self, memory),
            0xCA => ops.jp_z_nn(self, memory),
            0xCB => ops.prefix_cb(self, memory),
            0xCC => ops.call_z_nn(self, memory),
            0xCD => ops.call_nn(self, memory),
            0xCE => ops.adc_a_n(self, memory),
            0xCF => ops.rst_08(self, memory),
            0xD0 => ops.ret_nc(self, memory),
            0xD1 => ops.pop_de(self, memory),
            0xD2 => ops.jp_nc_nn(self, memory),
            0xD3 => {},
            0xD4 => ops.call_nc_nn(self, memory),
            0xD5 => ops.push_de(self, memory),
            0xD6 => ops.sub_a_n(self, memory),
            0xD7 => ops.rst_10(self, memory),
            0xD8 => ops.ret_c(self, memory),
            0xD9 => ops.reti(self, memory),
            0xDA => ops.jp_c_nn(self, memory),
            0xDB => {},
            0xDC => ops.call_c_nn(self, memory),
            0xDD => {},
            0xDE => ops.sbc_a_n(self, memory),
            0xDF => ops.rst_18(self, memory),
            0xE0 => ops.ldh_nn_a(self, memory),
            0xE1 => ops.pop_hl(self, memory),
            0xE2 => ops.ld_ff00_c_a(self, memory),
            0xE3 => {},
            0xE4 => {},
            0xE5 => ops.push_hl(self, memory),
            0xE6 => ops.and_n(self, memory),
            0xE7 => ops.rst_20(self, memory),
            0xE8 => ops.add_sp_n(self, memory),
            0xE9 => ops.jp_hl(self, memory),
            0xEA => ops.ld_nn_a(self, memory),
            0xEB => {},
            0xEC => {},
            0xED => {},
            0xEE => ops.xor_n(self, memory),
            0xEF => ops.rst_28(self, memory),
            0xF0 => ops.ldh_a_nn(self, memory),
            0xF1 => ops.pop_af(self, memory),
            0xF2 => ops.ld_a_from_c(self, memory),
            0xF3 => ops.di(self, memory),
            0xF4 => {},
            0xF5 => ops.push_af(self, memory),
            0xF6 => ops.or_n(self, memory),
            0xF7 => ops.rst_30(self, memory),
            0xF8 => ops.ld_hl_sp_n(self, memory),
            0xF9 => ops.ld_sp_hl(self),
            0xFA => ops.ld_a_nn(self, memory),
            0xFB => ops.ei(self, memory),
            0xFC => {},
            0xFD => {},
            0xFE => ops.cp_n(self, memory),
            0xFF => ops.rst_38(self, memory),
        }
    }
};
